name: "Build and Push Subdirectory"
description: "Log into GHCR, set up buildx with QEMU, build, push"
inputs:
  container-name:
    description: "Name of GHCR container to build"
    required: true
  build-directory:
    description: "Path containing Dockerfile to build"
    required: true
    default: "./"
  docker-tag:
    description: "Docker image tag"
    required: true
    default: "latest"
  github-token:
    description: "GitHub auth token for GHCR"
    required: true
runs:
  using: "composite"
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ inputs.github-token }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.build-directory }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ inputs.container-name }}:${{ inputs.docker-tag }}
