name: CI

on:
  push:
    branches: [galactic]
  pull_request:
    branches: [galactic]

  workflow_dispatch:

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./.github/workflows/scripts/build-and-push
        with:
          container-name: microros-base
          build-directory: base
          docker-tag: galactic
  build-agent:
    runs-on: ubuntu-latest
    needs: build-base
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./.github/workflows/scripts/build-and-push
        with:
          container-name: microros-agent
          build-directory: micro-ROS-Agent
          docker-tag: galactic
  build-demos:
    runs-on: ubuntu-latest
    needs: build-base
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./.github/workflows/scripts/build-and-push
        with:
          container-name: microros-demos
          build-directory: micro-ROS-demos
          docker-tag: galactic
  build-static-library-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./.github/workflows/scripts/build-and-push
        with:
          container-name: microros-static-library-builder
          build-directory: micro-ROS-static-library-builder
          docker-tag: galactic
